<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property boolean $show_expand - показывать ли в развернутом состоянии пункт меню
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'url'], 'required'],
            ['show_expand', 'boolean'],
            ['sort', 'integer'],
            [['name', 'url', 'title', 'meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255],
            ['description', 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'url' => 'Url',
            'show_expand' => 'показывать как главная',
        ];
    }

    public function beforeDelete()
    {
        //echo "test"; die();
        //Video::deleteAll('category_id = :category_id', [':category_id'=>$this->id]);

        $videos = Video::find()->where('category_id = :category_id', [':category_id'=>$this->id])->all();
        foreach($videos as $v){
            $v->delete();
        }


        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
