<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category_photo".
 *
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property integer $show_expand
 * @property string $description
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 */
class CategoryPhoto extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category_photo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'url'], 'required'],
            [['show_expand'], 'integer'],
            [['description'], 'string'],
            ['sort', 'integer'],
            [['name', 'url', 'title', 'meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'url' => 'Url',
            'show_expand' => 'показывать как главная',
            'description' => 'Description',
            'meta_title' => 'Meta Title',
            'meta_keywords' => 'Meta Keywords',
            'meta_description' => 'Meta Description',
        ];
    }

    public function beforeDelete()
    {

        $photos = PhotoCatalog::find()->where('category_id = :category_id', [':category_id'=>$this->id])->all();
        foreach($photos as $photo){
            $photo->delete();
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
